import type { NextPage } from 'next';
import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import 'bootstrap/dist/css/bootstrap.min.css';
import Header from '../../components/Navbar';
import Router from 'next/router';

const Home: NextPage = () => {
  const [user, setUser] = useState({
    first_name: null,
    last_name: null,
    avatar: null,
    email: null,
  });
  useEffect(() => {
    const getUser = async () => {
      const result = await fetch('https://reqres.in/api/users/2');
      const res = await result.json();
      setUser(res.data);
      if (res === null) Router.push('/login');
    };

    getUser().catch(console.error);
  }, []);
  const { email, first_name, last_name, avatar } = user;
  return (
    <>
      <div>
        <Head>
          <title>Logged In User</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.png' />
        </Head>
        <Header />
        <div className='container'>
          <h2 className='mt-4'>
            Welcome:{' '}
            <i>
              {first_name} {last_name}
            </i>
          </h2>
          <br />
          <a href='/user/account' className='btn btn-primary'>
            See Account
          </a>
        </div>
      </div>
    </>
  );
};

export default Home;
